using System;
using System.ComponentModel.DataAnnotations;

namespace Play.Catalog.Service.Dtos
{
    //I realized that most of this code is actuall generated by the compiler.
    /*
    public record ItemDto
    {
        public Guid Id { get; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public DateTimeOffset CreatedDate { get; set; }
        public ItemDto(Guid id, string name, string description, decimal price, DateTimeOffset createdDate)
            => (Id, Name, Description, Price, CreatedDate) = (id, name, description, price, createdDate);

        public void Deconstruct(out Guid id, out string name, out string description, out decimal price, out DateTimeOffset createdDate)
            => (id, name, description, price, createdDate) = (Id, Name, Description, Price, CreatedDate);

    }
    */
    public record ItemDto(Guid Id, string Name, string Description, decimal Price, DateTimeOffset CreatedDate);

    /*
        public record CreateItemDto
        {
            public string Name { get; set; }
            public string Description { get; set; }
            public decimal Price { get; set; }

            public CreateItemDto(string name, string description, decimal price) => (Name, Description, Price) = (name, description, price);
            public void Deconstruct(out string name, out string description, out decimal price) => (name, description, price) = (Name, Description, Price);

        }
        */

    public record CreateItemDto([Required] string Name, string Description, [Range(0, 1000)] decimal Price);
    /*
        public record UpdateItemDto
        {
            public string Name { get; set; }
            public string Description { get; set; }
            public decimal Price { get; set; }
            public UpdateItemDto(string name, string description, decimal price) => (Name, Description, Price) = (name, description, price);
            public void Deconstruct(out string name, out string description, out decimal price) => (name, description, price) = (Name, Description, Price);
        }
    */

    public record UpdateItemDto([Required] string Name, string Description, [Range(0, 1000)] decimal Price);

}